resolver: lts-8.13
packages:
- '.'
- location:
    git: git@github.com:shouhei/hscabocha.git
    commit: 0347467eca7fb63e3b1a88dea61b6e0805dd2186
flags: {}
extra-package-dbs: []
extra-deps: []
extra-include-dirs:
  - /usr/local/Cellar/cabocha/0.69/include
extra-lib-dirs:
  - /usr/local/Cellar/cabocha/0.69/lib/
